# lesson 12 numpy part 1

In [2]:
import numpy as np

In [3]:
# radians
a = np.sin(30)
b = np.cos(30)
c = np.tan(30)
print(a , b , c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [4]:
# degree
a = np.sin(30*np.pi/180)
b = np.cos(30*np.pi/180)
c = np.tan(30*np.pi/180)
print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [5]:
a = np.sin(deg2rad(30))
b = np.cos(deg2rad(30))
c = np.tan(deg2rad(30))
print(a)
print(b)
print(c)




NameError: name 'deg2rad' is not defined

In [ ]:
# round
a = np.round(3.68528)
b = np.round(3.68528,1)
c = np.round(3.68528,2)
d = np.round(3.68528,3)
e = np.round(3.68528,4)
print(a)
print(b)
print(c)
print(d)
print(e)

In [ ]:
# floor
a = np.floor(3.68528)
print(a)

In [ ]:
# ceil
a = np.ceil(3.68528)
print(a)

In [ ]:
# mod   %
a = np.mod(20,7)
print(a)

In [ ]:
# power  **
b = np.power(2,5)
print(b)

In [ ]:
# transform list to array 
a = [2,3,6,5,4,7,8]
b = np.array(a)
print(a)
print(b)

In [ ]:
# array in range
a = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(a)

In [ ]:
# can define varable after write
a = np.array([('x',3,4.2),('y',4,5.3),('z',5,6.3)])
print(a)
print('---------------------------------------------------------')
b=np.array([('x',3,4.2),('y',4,5.3),('z',5,6.3)],dtype =[('name','U5'),('number','i2'),('value','f4')])
print(b)

In [ ]:
# 2D array
a = [[1,2,3],[5,3,6],[9,6,5]]
b = np.array(a)
print(b)

In [ ]:
# empty array from 2 Row and 3 columns
a = np.empty((3,2))
print(a)

In [ ]:
# uniform make random values in range
a = np.random.uniform(1,10)
print(a)

In [ ]:
# uniform make random values in range and number of random value
b = np.random.uniform(1,10,20)
print(b)

In [ ]:
# rondom array from between 0 and 1
a =np.random.random((2,3))
print(a)

In [ ]:
# 10 numbers: 1 to 10
a =np.random.normal(0,1,10)
print(a)

In [ ]:
# random number between 0:150
a = np.random.randint(150)
print(a)

In [ ]:
# 7 random number between 0:5
a =np.random.randint(5, size=7)
print(a)

In [ ]:
# 7 random number between 5:20
a =np.random.randint(5,20, size=7)
print(a)

In [ ]:
# make array 3*3 with random number between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)

In [ ]:
# 3D
a = np.random.randint(5,10, size=(3, 4, 5))
print(a)

In [ ]:
# make 25 random number between 1:60
a = np.random.randint(1,60,25)
print(a)
print('-------------------------------------')
# reshape 25 random to array from 5*5
b = np.reshape(a,(5,5))
print(b)

In [ ]:
# 15 random number between 0:1
a = np.random.rand(15)
print(a)

In [ ]:
# make random 2D array
a = np.random.rand(5,3)
print(a)

In [ ]:
# make random 3D array
a = np.random.rand(5,3,2)
print(a)

In [ ]:
# choice random number from list
y=[1,2,3,6,8,5,4,7,8,9,6,5,9,6]
a = np.random.choice(y)
print(a)

In [ ]:
# choice more random number from list
y=[1,2,3,6,8,5,4,7,8,9,6,5,9,6]
a = np.random.choice(y,size=5)
print(a)

In [ ]:
# make random shuffl in list
y=[1,2,3,6,8,5,4,7,8,9,6,5,9,6]
print(y)
np.random.shuffle(y)
print(y)

In [ ]:
# make array 1D from zero or one
a = np.zeros(8)
b = np.ones(10)
print(a)
print(b)

In [ ]:
# make array 2D from zero or one
a = np.zeros((3,5))
b = np.ones((6,8))
print(a)
print(b)

In [ ]:
# make array 3D from zero or one
a = np.zeros((2,3,2))
b = np.ones((2,3,2))
print(a)
print(b)

In [ ]:
# Identity matrix
a = np.eye(5)
print(a)

In [ ]:
# make array from 3*5 and full all array with 35
a = np.full((3, 5), 35)
print(a)

In [ ]:
# make array from range 0:18 and reshape to 2D array
a =np.arange(18).reshape(3,6)
print(a)

In [ ]:
# make array from range 0:27 and reshape to 3D array
b =np.arange(27).reshape(3,3,3)
print(b)

In [ ]:
# To write numbers that are evenly distributed between two digits
b =np.linspace(0,30)
print(b)
print('------------------------------------')
# To write 5 numbers that are evenly distributed
c =np.linspace(0,100,5)
print(c)

In [ ]:
# to transform 12 number are evenly distributed between 0:30 to array from 3*4
b =np.linspace(0,30,12).reshape(3,4)
print(b)
print('------------------------------------')
# to transform 27 number are evenly distributed between 0:100 to array from 3*3*4
c =np.linspace(0,100,27).reshape(3,3,3)
print(c)

In [ ]:
# Diagonal Matrix
a =np.diag(np.array([5,12,4,-1,3]))
b =np.diag(np.array([5,12,4,-1,3]),k=3)
print(a)
print('------------------------------------')
print(b)

In [ ]:
# make array from 3*3 between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)
print('------------------------------------')
# count_nonzero in array from 3*3 between 0:10
b = np.count_nonzero(a)
print(b)

In [ ]:
# make array from 3*3 between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)
print('------------------------------------')
# count number applied in condition
b = np.count_nonzero(a>5)
print(b)
print('------------------------------------')
# count number applied in condition
c = np.count_nonzero(a<8)
print(c)

In [ ]:
# make array from 3*3 between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)
print('------------------------------------')
# count number applied in condition and columns
b = np.count_nonzero(a>5,axis=1)
print(b)
print('------------------------------------')
# count number applied in condition and columns
c = np.count_nonzero(a<8,axis=1)
print(c)

In [ ]:
# make array from 3*3 between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)
print('------------------------------------')
# count number applied in condition and columns
b = any(a>8)
print(b)

In [ ]:
# make array from 3*3 between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)
print('------------------------------------')
# count number applied in condition and columns
b = any(a>5,axis=1)
print(b)

In [ ]:
# make array from 3*3 between 0:10
a = np.random.randint(0, 10, (3, 3))
print(a)
print('------------------------------------')
b = all(a>5)
print(b)

In [ ]:
# make array from 3*3 between 5:20
a =np.random.randint(5,20, size=(3,3))
print(a)
print('-------------------------')
# make boolen array from 3*3 contain if condition true or false
b = a>10
print(b)
print('-------------------------')
# make boolen array from 3*3 contain if condition true or false
c = a<15
print(c)

In [ ]:
# compare between Two array
a =np.arange(9).reshape(3,3)
print(a)
print('-------------------------')
b =np.arange(9).reshape(3,3)
print(b)
print('-------------------------')
c = 2*b
print(c)
print('-------------------------')
d = np.isclose(a,b,rtol = 0.1)
print(d)
print('-------------------------')
e = np.isclose(a,c,rtol = 0.1)
print(e)

In [ ]:
# dot multiply between Two array
a =np.arange(5)
print(a)
print('-------------------------')
b =np.empty(5)
np.multiply(a, 10, out=b)
print(b)

In [ ]:
# to make array power to anther array
a =np.arange(5)
print(a)
print('-------------------------')
b =np.empty(5)
np.power(a, 4, out=b)
print(b)

In [ ]:
# sum of array
a =np.arange(15)
print(a)
print('-------------------------')
b = np.add.reduce(a)
print(b)

In [ ]:
# multiply of array
a =np.arange(2,8)
print(a)
print('-------------------------')
b = np.multiply.reduce(a)
print(b)

In [ ]:
# multiply array by array
a =np.arange(2,8)
print(a)
print('-------------------------')
b = np.multiply.outer(a,a)
print(b)

In [ ]:
# Add all the previous numbers
a =np.arange(10)
print(a)
print('-------------------------')
b = np.add.accumulate(a)
print(b)

In [ ]:
# multiply all the previous numbers
a =np.arange(2,8)
print(a)
print('-------------------------')
b = np.multiply.accumulate(a)
print(b)

In [ ]:
a =np.arange(12).reshape(4,3)
print(a)
print('-------------------------')
# to know how many Row or column in the array
b = a.shape
print(b)
print('-------------------------')
c = a.reshape(3,4)
print(c)
print('-------------------------')
d = len(c)
print(d)


In [ ]:
# to know the size of array
a =np.arange(12)
print(a)
print('-------------------------')
b = a.size
print(b)
print('-------------------------')
c = a.reshape(3,4)
print(c)
print('-------------------------')
d = c.size
print(d)

In [ ]:
# to know the shape of array
a =np.arange(12)
print(a)
print('-------------------------')
b = a.shape
print(b)
print('-------------------------')
c = a.reshape(3,4)
print(c)
print('-------------------------')
d = c.shape
print(d)

In [ ]:
# to know how Dimensions of array
a =np.arange(12)
print(a)
print('-------------------------')
b = a.ndim
print(b)
print('-------------------------')
c = a.reshape(3,4)
print(c)
print('-------------------------')
d = c.ndim
print(d)


In [ ]:
# to know data type in array
a =np.array(['a','d','g','h','j'])
print(a)
print('-------------------------')
b = a.dtype
print(b)
print('-------------------------')
c = np.arange(12)
print(c)
print('-------------------------')
d = c.reshape(3,4)
print(d)
print('-------------------------')
e = d.dtype
print(e)


In [ ]:
# make matrix
a = np.matrix('{} {} ; {} {}'.format(1,2,3,4))
print(a)
print('-------------------------')
b = np.matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6))
print(b)


In [ ]:
# trace
a =np.arange(9)
print(a)
print('-------------------------')
b = a.reshape(3,3)
print(b)
print('-------------------------')
c = np.trace(b)
print(c)


In [ ]:
a =np.arange(4)
print(a)
print('-------------------------')
b = a.reshape(2,2)
print(b)
print('-------------------------')
# det value 
c = np.linalg.det(b)
print(c)
print('-------------------------')
# eig value 
d = np.linalg.eig(b)
print(d)

In [ ]:
# Slicing Array
a =np.arange(10)
print(a)
print('-------------------------')
c = a[3]
print(c)
print('-------------------------')
d = a[3:9]
print(d)
print('-------------------------')
e = a[3:9:2]
print(e)
print('-------------------------')
f = a[-1]
print(f)
print('-------------------------')
g = a[-3]
print(g)

In [ ]:
# example
a =np.arange(36).reshape(6,6)
print(a)
print('--------')
c = a[3]
print(c)
print('--------')
d = a[3:9]
print(d)
print('--------')
e = a[3:9:2]
print(e)
print('--------')
f = a[-1]
print(f)
print('--------')
g = a[-3]
print(g)

In [ ]:
# example
a =np.arange(36).reshape(6,6)
print(a)
print('--------')
c = a[3,1]
print(c)
print('--------')
d = a[3,:]
print(d)
print('--------')
e = a[:,2]
print(e)
print('--------')
f = a[:,1:3]
print(f)
print('--------')
g = a[1:2,:]
print(g)

In [ ]:
#example
a =np.arange(36).reshape(6,6)
print(a)
print('--------')
c = a[3:4,1:5]
print(c)
print('--------')
d = a[2:,3:]
print(d)
print('--------')
e = a[:2,:3]
print(e)
print('--------')
f = a[:,-1]
print(f)
print('--------')
g = a[-1,:]
print(g)

In [ ]:
#example
a =np.arange(36).reshape(6,6)
print(a)
print('--------')
c = a[ :: 2, :: 3]
print(c)
print('--------')
d = a[ ::- 1, ::- 1]
print(d)
print('--------')
e = a[:2 :- 1,:3 :- 1]
print(e)
print('--------')
f = a[2 :: 2,3 :: 3]
print(f)
print('--------')
g = a[-1 :: ,-1 :: ]
print(g)

In [ ]:
# edit value in array
a =np.arange(16).reshape(4,4)
print(a)
print('--------')
a[2,3] =0
print(a)
print('--------')
a[:,3] = 0
print(a)
print('--------')
a[2,:] = 0
print(a)
print('--------')
a[:,:] = 0
print(a)

In [ ]:
# النسخة المربوطة
a =np.arange(16).reshape(4,4)
print(a)
print('--------')
b = a[:, 1:3]
print(b)
print('--------')
a[:,:] = 5
print(a)
print('--------')
print(b)


In [ ]:
# copy in array
a =np.arange(16).reshape(4,4)
print(a)
print('-------------------------')
b = a[:,1:3].copy()
print(b)
print('-------------------------')
a[:,:] = 5
print(a)
print('-------------------------')
print(b)

In [ ]:
# 3D array
a =np.arange(18).reshape(3,3,2)
print(a)
print('-------------------------')
c = a[1]
print(c)
print('-------------------------')
d = a[1,2]
print(d)
print('-------------------------')
e = a[2,2,1]
print(e)

In [ ]:
# split
x = [11,22,33,44,55,66,77,88]
x1, x2, x3 = np.split(x, (3,6))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = np.split(x, (1,5))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = np.split(x, (6, 3))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = np.split(x, (0, 3))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = np.split(x, (4, 0))
print(x1, x2, x3)

In [ ]:
# Selecting an item
a =np.arange(16).reshape(4,4)
print(a)
print('-------------------------')
b = a[2][1]
print(b)

In [ ]:
# Vertical merge
a =np.arange(4).reshape(2,2)
print(a)
print('-------------------------')
b =2*np.arange(4).reshape(2,2)
print(b)
print('-------------------------')
c = np.vstack((a,b))
print(c)

In [ ]:
# horizontal merge
a =np.arange(4).reshape(2,2)
print(a)
print('-------------------------')
b =2*np.arange(4).reshape(2,2)
print(b)
print('-------------------------')
c = np.hstack((a,b))
print(c)

In [ ]:
# concatenate axis = 0
a =np.random.randint(5,20, size=9).reshape(3,3)
b =np.random.randint(5,20, size=9).reshape(3,3)
c = np.concatenate([a,b] , axis = 0)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[ 5 15 13]
 [11 19 12]
 [16  5 16]]
-------------------------
[[15 12  7]
 [19 11 10]
 [13  9 12]]
-------------------------
[[ 5 15 13]
 [11 19 12]
 [16  5 16]
 [15 12  7]
 [19 11 10]
 [13  9 12]]
-------------------------


In [ ]:
# concatenate axis = 1
a =np.random.randint(5,20, size=9).reshape(3,3)
b =np.random.randint(5,20, size=9).reshape(3,3)
c = np.concatenate([a,b] , axis = 1)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
