# lesson 12 numpy part 2

In [57]:
import numpy as np

In [58]:
# max and min
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = np.max(a)
print(b)
print('-------------------------')
c = np.min(a)
print(c)
print('-------------------------')
d = np.argmax(a)
print(d)
print('-------------------------')
e = np.argmin(a)
print(e)

[[13  5  7]
 [19 11 13]
 [ 5 16  7]]
-------------------------
19
-------------------------
5
-------------------------
3
-------------------------
1


In [59]:
# Variance and Covariance
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = np.var(a)
print(b)
print('-------------------------')
c = np.cov(a)
print(c)

[[15 12 10]
 [ 9 13 10]
 [13 18 17]]
-------------------------
8.88888888888889
-------------------------
[[ 6.33333333 -1.83333333 -5.5       ]
 [-1.83333333  4.33333333  4.5       ]
 [-5.5         4.5         7.        ]]


In [60]:
# + - 
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b =np.random.randint(5,20, size=9).reshape(3,3)
print(b)
print('-------------------------')
c = a+b
print(c)
print('-------------------------')
d = a-b
print(d)


[[10  6 17]
 [18 13 19]
 [11 18 15]]
-------------------------
[[17 12  8]
 [ 8 14 14]
 [ 9 14 12]]
-------------------------
[[27 18 25]
 [26 27 33]
 [20 32 27]]
-------------------------
[[-7 -6  9]
 [10 -1  5]
 [ 2  4  3]]


In [61]:
# * /
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b =np.random.randint(5,20, size=9).reshape(3,3)
print(b)
print('-------------------------')
c = a*b
print(c)
print('-------------------------')
d = a/b
print(d)

[[ 5 12 15]
 [14 19 14]
 [10 17 11]]
-------------------------
[[ 9 19 11]
 [19  8 13]
 [11 15  6]]
-------------------------
[[ 45 228 165]
 [266 152 182]
 [110 255  66]]
-------------------------
[[0.55555556 0.63157895 1.36363636]
 [0.73684211 2.375      1.07692308]
 [0.90909091 1.13333333 1.83333333]]


In [62]:
# Dividing and multiplying the matrix by a number
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b =np.random.randint(5,20, size=9).reshape(3,3)
print(b)
print('-------------------------')
c = a*3
print(c)
print('-------------------------')
d = b/5
print(d)

[[ 7 17 18]
 [ 8  6 17]
 [14 10 13]]
-------------------------
[[ 6 13 16]
 [18  5 17]
 [11 13 18]]
-------------------------
[[21 51 54]
 [24 18 51]
 [42 30 39]]
-------------------------
[[1.2 2.6 3.2]
 [3.6 1.  3.4]
 [2.2 2.6 3.6]]


In [63]:
# function matrix
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b =np.random.randint(5,20, size=9).reshape(3,3)
print(b)
print('-------------------------')
c = np.sin(a)
print(c)
print('-------------------------')
d = b**2
print(d)
print('-------------------------')
e = np.log(a)
print(e)

[[15 11  8]
 [12 10 16]
 [12  7  8]]
-------------------------
[[ 9  7 16]
 [ 9  7 18]
 [10 17  8]]
-------------------------
[[ 0.65028784 -0.99999021  0.98935825]
 [-0.53657292 -0.54402111 -0.28790332]
 [-0.53657292  0.6569866   0.98935825]]
-------------------------
[[ 81  49 256]
 [ 81  49 324]
 [100 289  64]]
-------------------------
[[2.7080502  2.39789527 2.07944154]
 [2.48490665 2.30258509 2.77258872]
 [2.48490665 1.94591015 2.07944154]]


In [64]:
# dot
a =np.random.randint(1,4, size=9).reshape(3,3)
print(a)
print('-------------------------')
b =np.random.randint(1,4, size=9).reshape(3,3)
print(b)
print('-------------------------')
c = np.dot(a,b)
print(c)

[[2 3 1]
 [1 1 2]
 [1 3 1]]
-------------------------
[[3 1 3]
 [1 2 2]
 [2 3 1]]
-------------------------
[[11 11 13]
 [ 8  9  7]
 [ 8 10 10]]


In [65]:
# sum
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = sum(a)
print(b)
print('-------------------------')
c = a.sum()
print(c)
print('-------------------------')
d = a.sum(axis = 1)
print(d)
print('-------------------------')
e = a.sum(axis = 0)
print(e)


[[ 6 12 19]
 [16 12 16]
 [ 9 13  5]]
-------------------------
108
-------------------------
108
-------------------------
[37 44 27]
-------------------------
[31 37 40]


In [66]:
# mean and std and var
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = a.mean()
print(b)
print('-------------------------')
c = a.std()
print(c)
print('-------------------------')
d = a.var()
print(d)

[[14 17 15]
 [18 18 13]
 [ 7  8  7]]
-------------------------
13.0
-------------------------
4.320493798938574
-------------------------
18.666666666666668


In [67]:
# corrcoef
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = np.corrcoef(a)
print(b)

[[18  9 19]
 [ 7 14 12]
 [13 14  6]]
-------------------------
[[ 1.         -0.65465367 -0.66647385]
 [-0.65465367  1.         -0.12725695]
 [-0.66647385 -0.12725695  1.        ]]


In [68]:
# sort Row and Columns
a =np.random.randint(5,20, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = np.sort(a,axis=0)
print(b)
print('-------------------------')
c = np.sort(a,axis=1)
print(c)

[[11 15  8]
 [19 17 10]
 [19 11 14]]
-------------------------
[[11 11  8]
 [19 15 10]
 [19 17 14]]
-------------------------
[[ 8 11 15]
 [10 17 19]
 [11 14 19]]


In [69]:
# inv
a =np.random.randint(1,4, size=9).reshape(3,3)
print(a)
print('-------------------------')
b = np.linalg.inv(a)
print(b)
print('-------------------------')
c = np.dot(a,b)
print(c)

[[2 1 3]
 [2 3 3]
 [2 2 2]]
-------------------------
[[ 0.  -1.   1.5]
 [-0.5  0.5  0. ]
 [ 0.5  0.5 -1. ]]
-------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:
# Polynomial
Polynomial = np.polynomial.Polynomial
X= np.array([0,20,40,60,80,100,120,140,160,180])
Y= np.array([10,9,8,7,6,5,4,3,2,1])
points,stats = Polynomial.fit(X,Y,1,full=True)
print(points)
print('-------------------------')
print(stats)


5.5 - 4.5 (-1.0 + 0.01111111x)
-------------------------
[array([5.62063395e-30]), np.int32(2), array([1., 1.]), np.float64(2.220446049250313e-15)]


In [71]:
# Poly
a = np.poly1d((-7))
print(a)
print('-------------------------')
b = np.poly1d((-7,2))
print(b)
print('-------------------------')
c = np.poly1d((-7,2,1))
print(c)
print('-------------------------')
d = np.poly1d((-7,2,1,3))
print(d)
print('-------------------------')
e = np.poly1d((-7,2,1,3,6))
print(e)


 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
-------------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6


In [72]:
# make x equal number
a = np.poly1d((-7,2,1,3,6))
print(a)
print('-------------------------')
b=a(5)
print(b)
print('-------------------------')
c=a(0)
print(c)
print('-------------------------')
d=a(-15)
print(d)

    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
-------------------------
-4079
-------------------------
6
-------------------------
-360939


In [73]:
# the same order
a= np.polyval((-7,2,1,3,6),5)
# a = polyval((1,2),2)
# b = polyval((1,2,3),7)
# c = polyval((1,2,3,5),-3)
# d = polyval((1,2,3,5,-6),12.6)

print(a)
# print('-------------------------')
# print(b)
# print('-------------------------')
# print(c)
# print('-------------------------')
# print(d)


-4079


In [74]:
# derivation
a1=np.poly1d((1,2,3))
print(a1)
a =np.polyder(a1)
print('-------------------------')
print(a)

   2
1 x + 2 x + 3
-------------------------
 
2 x + 2


In [75]:
#  make x equal number in derivation
a =np.polyder(np.poly1d((1,2,3)))
print(a(2))
print('-------------------------')
b =np.polyder(np.poly1d((1,2,3)),2)
print(b(0))
print('-------------------------')
c =np.polyder(np.poly1d((1,2,3)),3)
print(c(3))
print('-------------------------')
d =np.polyder(np.poly1d((1,2,3,5,12)))
print(d(-1))
print('-------------------------')
e =np.polyder(np.poly1d((1,2,3,5,12)),3)
print(e(5))

6
-------------------------
2
-------------------------
0
-------------------------
1
-------------------------
132


In [76]:
# Integration
a =np.polyint(np.poly1d((1,2,3)))
print(a)
print('-------------------------')
b =np.polyint(np.poly1d((1,2,3)),2)
print(b)
print('-------------------------')
c =np.polyint(np.poly1d((1,2,3)),3)
print(c)
print('-------------------------')
d =np.polyint(np.poly1d((1,2,3,5,12)))
print(d)
print('-------------------------')
e =np.polyint(np.poly1d((1,2,3,5,12)),3)
print(e)

        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
-------------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 2.5 x + 12 x
-------------------------
          7           6        5          4     3
0.004762 x + 0.01667 x + 0.05 x + 0.2083 x + 2 x


In [77]:
# make x equal number in Integration
a =np.polyint(np.poly1d((1,2,3)))
print(a(2))
print('-------------------------')
b =np.polyint(np.poly1d((1,2,3)),2)
print(b(0))
print('-------------------------')
c =np.polyint(np.poly1d((1,2,3)),3)
print(c(3))
print('-------------------------')
d =np.polyint(np.poly1d((1,2,3,5,12)))
print(d(-1))
print('-------------------------')
e =np.polyint(np.poly1d((1,2,3,5,12)),3)
print(e(5))

12.666666666666666
-------------------------
0.0
-------------------------
24.300000000000004
-------------------------
-10.2
-------------------------
1168.8988095238094


In [78]:
# roots
a =np.roots(np.poly1d((1,2)))
print(a)
print('-------------------------')
b =np.roots(np.poly1d((1,2,3)))
print(b)
print('-------------------------')
c =np.roots(np.poly1d((1,2,3,5)))
print(c)
print('-------------------------')
d =np.roots(np.poly1d((1,2,3,5,12)))
print(d)
print('-------------------------')
e =np.roots(np.poly1d((1,2,3,5,12,22)))
print(e)
print('-------------------------')
a=np.poly1d((1,2,3,4,4))
print(a)
print('-------------------------')
a1=np.roots(a)
print(a1)

[-2.]
-------------------------
[-1.+1.41421356j -1.-1.41421356j]
-------------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
-------------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
-------------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]
-------------------------
   4     3     2
1 x + 2 x + 3 x + 4 x + 4
-------------------------
[ 0.20710678+1.39896633j  0.20710678-1.39896633j -1.20710678+0.73681288j
 -1.20710678-0.73681288j]


In [79]:
# polyfit
x = np.array([3,6,2,5,4])
print(x)
print('-------------------------')
y = np.array([2,3,-9,6,2.5])
print(y)
print('-------------------------')
z = np.polyfit(x, y,3)
print(z)

[3 6 2 5 4]
-------------------------
[ 2.   3.  -9.   6.   2.5]
-------------------------
[  0.33333333  -5.78571429  31.95238095 -52.1       ]


In [80]:
# Formulation Date
x = np.array('2015-07-04', dtype=datetime64)
print(x)

2015-07-04


In [81]:
# Example
x = np.datetime64('2015-07-04')
print(x)

2015-07-04


In [82]:
# Increased days
x = np.datetime64('2015-07-04')
print(x)
print('-------------------------')
y = x + np.arange(12)
print(y)

2015-07-04
-------------------------
['2015-07-04' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-07-09' '2015-07-10' '2015-07-11' '2015-07-12' '2015-07-13'
 '2015-07-14' '2015-07-15']


In [83]:
# decrease days
x = np.datetime64('2015-07-04')
print(x)
print('-------------------------')
y = x - np.arange(12)
print(y)

2015-07-04
-------------------------
['2015-07-04' '2015-07-03' '2015-07-02' '2015-07-01' '2015-06-30'
 '2015-06-29' '2015-06-28' '2015-06-27' '2015-06-26' '2015-06-25'
 '2015-06-24' '2015-06-23']


In [84]:
# Difference of days
X = np.datetime64('2015-07-04')
print(x)
print('-------------------------')
y = np.datetime64('2018-09-21')
print(y)
print('-------------------------')
Z = y-x
print(z)

2015-07-04
-------------------------
2018-09-21
-------------------------
[  0.33333333  -5.78571429  31.95238095 -52.1       ]


In [85]:
# Numpy Function
# fromfunction
x = np.fromfunction(lambda i: i**3, (10,))
print(x)

[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]


In [86]:
# 1D
x = np.fromfunction(lambda i: 3 * (i+5)**3, (10,))
print(x)

[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]


In [87]:
# 2D
x = np.fromfunction(lambda i,j: i+j, (4,5))
print(x)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]


In [88]:
# Example
x = np.fromfunction(lambda i,j: 3*i*j, (4,5))
print(x)

[[ 0.  0.  0.  0.  0.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  6. 12. 18. 24.]
 [ 0.  9. 18. 27. 36.]]


In [89]:
# 3D
x = np.fromfunction(lambda i,j,k: i+j+k, (2,3,4))
print(x)

[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]


In [90]:
# Example
x = np.fromfunction(lambda i,j,k: (2*i)+(j**2)*k, (2,3,4))
print(x)

[[[ 0.  0.  0.  0.]
  [ 0.  1.  2.  3.]
  [ 0.  4.  8. 12.]]

 [[ 2.  2.  2.  2.]
  [ 2.  3.  4.  5.]
  [ 2.  6. 10. 14.]]]


In [91]:
# different way
def powers(i):
    i = i**2
    return i
x = np.fromfunction(powers, (9,), dtype=int)
print(x)

[ 0  1  4  9 16 25 36 49 64]


In [92]:
# Example
def powers(i,j):
    i = i**j
    return i
x = np.fromfunction(powers, (4,5), dtype=int)
print(x)

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
